#include "DataFormats/HGCalReco/interface/HGCalSoAClustersHostCollection.h"
#include "DataFormats/HGCalReco/interface/HGCalSoARecHitsExtraHostCollection.h"
#include "DataFormats/HGCalReco/interface/HGCalSoARecHitsHostCollection.h"
#include "HeterogeneousCore/TrivialSerialisation/interface/SerialiserFactory.h"

DEFINE_TRIVIAL_SERIALISER_PLUGIN(HGCalSoAClustersHostCollection);
DEFINE_TRIVIAL_SERIALISER_PLUGIN(HGCalSoARecHitsExtraHostCollection);
DEFINE_TRIVIAL_SERIALISER_PLUGIN(HGCalSoARecHitsHostCollection);
